### ISSUE TITLE
error when creating raid without legacy data

### ISSUE THREAD

**Issue by scottrepreneur** [raid-guild/dungeon-master-api#26]
`Cannot return null for non-nullable field RaidLegacy.airtable_id`

creating the raid record from here:
https://github.com/raid-guild/dungeon-master-frontend/blob/1da3ad011e63e604a0c944ff25a215932886c849/pages/consultations/%5Bid%5D/index.tsx#L37

causes a crash in the return query
https://github.com/raid-guild/dungeon-master-frontend/blob/1da3ad011e63e604a0c944ff25a215932886c849/graphql/queries/raids.ts#L210

**Comment by manolingam** [comment]
The `airtable_id`  in legacy object was previously made not null in the typedefs which is fixed now.
