### ISSUE TITLE
Error in query when RaidParty doesn't exist

### ISSUE THREAD

**Issue by jonathanprozzi** [raid-guild/dungeon-master-api#28]
```
type RaidParty {
    _id: ID!
    members: [Member!]!
    raid: Raid!
    createdAt: String!
    updatedAt: String!
  }
```

I think we need this to be able to be nullable -- not all Raids in our db have this set and the query is currently failing.
@manolingam 

Some of our lost raids don't have a Raid Party set and are causing the query to error. We should be able to fix this by making members nullable, and I'll handle the null check on the frontend when we look for the data.

![image](https://user-images.githubusercontent.com/9438776/141717739-646d5aa1-a8f1-4713-a640-804e28fcbe06.png)

**Comment by manolingam** [comment]
This was fixed & so closing the issue.
